version: "3.8"
services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ../backend
    ports:
      - "8000:8000"
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
volumes:
  postgres_data
