version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    networks:
      - backend-network

  backend:
    build: ../backend
    ports:
      - "8000:8000"
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/todo
      SECRET_KEY: secret
    depends_on:
      - db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
volumes:
  postgres_data:
